insert into user (id, name, gender, username, email, facebook_account, twitter_account, google_account, registration_date) values (1, 'Sandro Simas', 'MALE', 'sandro.csimas', 'sandro.csimas@gmail.com', '654264634643651', null, null, '2014-04-27 11:19:10');

insert into political_party (id, name, acronym) values (1, 'Partido dos Trabalhadores', 'PT');

insert into political_office (id, title) values (1, 'Presidente');

insert into politician (id, name, nickname, slug, photo_path, biography, email, state_id, political_party_id, political_organ_id, political_office_id, registered_by_user_id, registration_date) values (1, 'Dilma Rousseff', null, 'dilma-rousseff', 'dilma-rousseff.jpg', 'Economista e política brasileira, filiada ao Partido dos Trabalhadores (PT), e a atual presidente da República Federativa do Brasil.', null, null, 1, null, 1, 1, '2014-04-27 11:20:10');

insert into politician_cover_photo(id, photo_path, politician_id) values (1, 'brazil-flag.jpg', 1);

insert into promise_category (id, name, slug) values (1, 'Saúde', 'saude');
insert into promise_category (id, name, slug) values (2, 'Programas Sociais e de Inclusão', 'programas-sociais-e-inclusao');
insert into promise_category (id, name, slug) values (3, 'Educação e Qualificação', 'educacao-e-qualificacao');
insert into promise_category (id, name, slug) values (4, 'Ciência e Tecnologia', 'ciencia-e-tecnologia');
insert into promise_category (id, name, slug) values (5, 'Esporte e Lazer', 'esporte-e-lazer');
insert into promise_category (id, name, slug) values (6, 'Copa e Olimpíadas', 'copa-e-olimpiadas');
insert into promise_category (id, name, slug) values (7, 'Habitação', 'habitacao');
insert into promise_category (id, name, slug) values (8, 'Urbanização', 'urbanizacao');
insert into promise_category (id, name, slug) values (9, 'Segurança e Defesa', 'seguranca-e-defesa');
insert into promise_category (id, name, slug) values (10, 'Transporte e Infraestrutura', 'transporte-e-infraestrutura');
insert into promise_category (id, name, slug) values (11, 'Emprego e Renda', 'emprego-e-renda');
insert into promise_category (id, name, slug) values (12, 'Impostos', 'impostos');
insert into promise_category (id, name, slug) values (13, 'Administração', 'administracao');
insert into promise_category (id, name, slug) values (14, 'Contas Públicas', 'contas-publicas');
insert into promise_category (id, name, slug) values (15, 'Macroeconomia e Finanças', 'macroeconomia-e-financas');
insert into promise_category (id, name, slug) values (16, 'Indústria', 'industria');
insert into promise_category (id, name, slug) values (17, 'Pequenas Empresas', 'pequenas-empresas');
insert into promise_category (id, name, slug) values (18, 'Petróleo', 'petroleo');
insert into promise_category (id, name, slug) values (19, 'Outras Fontes de Energia', 'outras-fontes-de-energia');
insert into promise_category (id, name, slug) values (20, 'Meio Ambiente', 'meio-ambiente');
insert into promise_category (id, name, slug) values (21, 'Reforma Agrária e Agricultura', 'reforma-agraria-e-agricultura');
insert into promise_category (id, name, slug) values (22, 'Irrigação', 'irrigacao');
insert into promise_category (id, name, slug) values (23, 'Família e Religião', 'familia-e-religiao');
insert into promise_category (id, name, slug) values (24, 'Cultura', 'cultura');
insert into promise_category (id, name, slug) values (25, 'Mídia e Livre Expressão', 'midia-e-livre-expressao');
insert into promise_category (id, name, slug) values (26, 'Política Externa', 'politica-externa');

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Melhorar todo o sistema de saúde.',NULL,'melhorar-todo-o-sistema-de-saude',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer 500 Unidades de Pronto Atendimento (UPAs) 24 horas.',NULL,'fazer-500-unidades-de-pronto-atendimento-(upas)-24-horas',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir 8.600 unidades básicas de saúde em todo o país.',NULL,'construir-8-600-unidades-basicas-de-saude-em-todo-o-pais',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Universalizar o SUS, garantindo mais recursos para o programa, e ampliar o número de profissionais.',NULL,'universalizar-o-sus-garantindo-mais-recursos-para-o-programa-e-ampliar-o-numero-de-profissionais',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Implantar o cartão do SUS, com o registro do histórico dos atendimentos.',NULL,'implantar-o-cartao-do-sus-com-o-registro-do-historico-dos-atendimentos',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Saúde da Família.',NULL,'ampliar-o-saude-da-familia',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar as Farmácias Populares.',NULL,'ampliar-as-farmacias-populares',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Brasil Sorridente.',NULL,'ampliar-o-brasil-sorridente',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Serviço de Atendimento Móvel de Urgência (Samu).',NULL,'ampliar-o-servico-de-atendimento-movel-de-urgencia-(samu)',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Valorizar práticas preventivas.',NULL,'valorizar-praticas-preventivas',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Garantir atendimento básico, ambulatorial e hospitalar altamente resolutivo em todos os estados.',NULL,'garantir-atendimento-basico-ambulatorial-e-hospitalar-altamente-resolutivo-em-todos-os-estados',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Melhorar a gestão dos recursos.',NULL,'melhorar-a-gestao-dos-recursos',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Distribuir gratuitamente remédios para hipertensão e diabetes, usando o programa Aqui tem Farmácia Popular.',NULL,'distribuir-gratuitamente-remedios-para-hipertensao-e-diabetes-usando-o-programa-aqui-tem-farmacia-popular',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Implantar rede de prevenção de câncer em todo o país',NULL,'implantar-rede-de-prevencao-de-cancer-em-todo-o-pais',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar a rede de atendimento para gestantes e crianças de até um ano. Criar clínicas especializadas, maternidades de alto e baixo riscos, UTIs neonatais e ambulâncias do Samu com mini-UTI para bebês, articulando essa rede ao Samu-Cegonha.',NULL,'ampliar-a-rede-de-atendimento-para-gestantes-e-criancas-de-ate-um-ano-criar-clinicas-especializadas-maternidades-de-alto-e-baixo-riscos-utis-neonatais-e-ambulancias-do-samu-com-mini-uti-para-bebes-articulando-essa-rede-ao-samu-cegonha',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Articular uma rede integrada pública e privada, custeada pelo SUS, para tratar dependentes de crack. O SUS deverá dar acompanhamento psicossocial após a internação.',NULL,'articular-uma-rede-integrada-publica-e-privada-custeada-pelo-sus-para-tratar-dependentes-de-crack-o-sus-devera-dar-acompanhamento-psicossocial-apos-a-internacao',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar atenção a programas de saúde mental, especialmente para tratamento de alcoolismo e dependência de drogas.',NULL,'dar-atencao-a-programas-de-saude-mental-especialmente-para-tratamento-de-alcoolismo-e-dependencia-de-drogas',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Acabar com as filas para exames e atendimentos especializados.',NULL,'acabar-com-as-filas-para-exames-e-atendimentos-especializados',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar cursos de capacitação para quem atende à população.',NULL,'criar-cursos-de-capacitacao-para-quem-atende-a-populacao',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ter autossuficiência científica na produção de fármacos.',NULL,'ter-autossuficiencia-cientifica-na-producao-de-farmacos',NULL,'NONE',1,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar a fabricação de genéricos.',NULL,'ampliar-a-fabricacao-de-genericos',NULL,'NONE',1,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Erradicar a miséria e conduzir os brasileiros ao padrão da classe média, melhorando a vida de 21,5 milhões de pessoas que vivem na pobreza absoluta.',NULL,'erradicar-a-miseria-e-conduzir-os-brasileiros-ao-padrao-da-classe-media-melhorando-a-vida-de-215-milhoes-de-pessoas-que-vivem-na-pobreza-absoluta',NULL,'NONE',2,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar reduzindo as desigualdades.',NULL,'continuar-reduzindo-as-desigualdades',NULL,'NONE',2,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar programas, em especial o Bolsa Família, e implantar novos.',NULL,'ampliar-programas-em-especial-o-bolsa-familia-e-implantar-novos',NULL,'NONE',2,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Bolsa Família para famílias sem filhos.',NULL,'ampliar-o-bolsa-familia-para-familias-sem-filhos',NULL,'NONE',2,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar as iniciativas de promoção de igualdade de direitos e oportunidades para mulheres, negros, populações indígenas, idosos e setores discriminados.',NULL,'ampliar-as-iniciativas-de-promocao-de-igualdade-de-direitos-e-oportunidades-para-mulheres-negros-populacoes-indigenas-idosos-e-setores-discriminados',NULL,'NONE',2,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Lutar pela inserção plena de portadores de deficiências.',NULL,'lutar-pela-insercao-plena-de-portadores-de-deficiencias',NULL,'NONE',2,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Aumentar para 7% do PIB os investimentos públicos em educação.',NULL,'aumentar-para-7-do-pib-os-investimentos-publicos-em-educacao',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Erradicar o analfabetismo.',NULL,'erradicar-o-analfabetismo',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar prioridade à qualidade da educação.',NULL,'dar-prioridade-a-qualidade-da-educacao',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir seis mil creches e pré-escolas.',NULL,'construir-seis-mil-creches-e-pre-escolas',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar bolsa de estudos e apoio para que os alunos não abandonem a escola. ',NULL,'dar-bolsa-de-estudos-e-apoio-para-que-os-alunos-nao-abandonem-a-escola',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar especial atenção à formação continuada de professores para os níveis fundamental e médio.',NULL,'dar-especial-atencao-a-formacao-continuada-de-professores-para-os-niveis-fundamental-e-medio',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Possibilitar que os professores tenham, ao menos, curso universitário e remuneração condizente com sua importância.',NULL,'possibilitar-que-os-professores-tenham-ao-menos-curso-universitario-e-remuneracao-condizente-com-sua-importancia',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter um piso salarial nacional para professores.',NULL,'manter-um-piso-salarial-nacional-para-professores',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Equipar as escolas com banda larga gratuita.',NULL,'equipar-as-escolas-com-banda-larga-gratuita',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir mais escolas federais.',NULL,'construir-mais-escolas-federais',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Proteger as crianças e os jovens da violência, do assédio das drogas e da imposição do trabalho em detrimento da formação escolar e acadêmica.',NULL,'proteger-as-criancas-e-os-jovens-da-violencia-do-assedio-das-drogas-e-da-imposicao-do-trabalho-em-detrimento-da-formacao-escolar-e-academica',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir escolas técnicas em municípios com mais de 50 mil habitantes ou que sejam polos de regiões.',NULL,'construir-escolas-tecnicas-em-municipios-com-mais-de-50-mil-habitantes-ou-que-sejam-polos-de-regioes',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar o ProMédio, programa de bolsa de estudo em instituições de ensino médio técnico, nos moldes do Universidade para Todos (ProUni).',NULL,'criar-o-promedio-programa-de-bolsa-de-estudo-em-instituicoes-de-ensino-medio-tecnico-nos-moldes-do-universidade-para-todos-(prouni)',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar vagas em escolas privadas também por meio de financiamento com prazos longos e juros baixos. Se o aluno formado prestar serviço civil, terá desconto grande, chegando a 100% se for técnico de saúde.',NULL,'criar-vagas-em-escolas-privadas-tambem-por-meio-de-financiamento-com-prazos-longos-e-juros-baixos-se-o-aluno-formado-prestar-servico-civil-tera-desconto-grande-chegando-a-100-se-for-tecnico-de-saude',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Garantir a qualificação do ensino universitário, com ênfase na pós-graduação.',NULL,'garantir-a-qualificacao-do-ensino-universitario-com-enfase-na-pos-graduacao',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir e interiorizar as universidades federais.',NULL,'expandir-e-interiorizar-as-universidades-federais',NULL,'NONE',3,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o ProUni.',NULL,'ampliar-o-prouni',NULL,'NONE',3,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer a inclusão digital, com banda larga em todo o país.',NULL,'fazer-a-inclusao-digital-com-banda-larga-em-todo-o-pais',NULL,'NONE',4,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Transformar o Brasil em potência científica e tecnológica.',NULL,'transformar-o-brasil-em-potencia-cientifica-e-tecnologica',NULL,'NONE',4,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar ênfase à formação de engenheiros.',NULL,'dar-enfase-a-formacao-de-engenheiros',NULL,'NONE',4,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir recursos para pesquisa e ampliar as bolsas da Capes e e do CNPq.',NULL,'expandir-recursos-para-pesquisa-e-ampliar-as-bolsas-da-capes-e-e-do-cnpq',NULL,'NONE',4,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o registro de patentes.',NULL,'ampliar-o-registro-de-patentes',NULL,'NONE',4,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Privilegiar as pesquisas em biotecnologia; nanotecnologia; robótica; novos materiais; tecnologia da informação e da comunicação; saúde e produção de fármacos; biocombustíveis e energias renováveis; agricultura; biodiversidade; Amazônia e semiárido; área n',NULL,'privilegiar-as-pesquisas-em-biotecnologia-nanotecnologia-robotica-novos-materiais-tecnologia-da-informacao-e-da-comunicacao-saude-e-producao-de-farmacos-biocombustiveis-e-energias-renovaveis-agricultura-biodiversidade-amazonia-e-semiarido-area-n',NULL,'NONE',4,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir seis mil quadras poliesportivas em escolas públicas com mais de 500 alunos.',NULL,'construir-seis-mil-quadras-poliesportivas-em-escolas-publicas-com-mais-de-500-alunos',NULL,'NONE',5,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Cobrir quatro mil quadras existentes.',NULL,'cobrir-quatro-mil-quadras-existentes',NULL,'NONE',5,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Investir na formação de atletas até 2014.',NULL,'investir-na-formacao-de-atletas-ate-2014',NULL,'NONE',5,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir 800 complexos esportivos, culturais e de lazer, em todos os lugares do país.',NULL,'construir-800-complexos-esportivos-culturais-e-de-lazer-em-todos-os-lugares-do-pais',NULL,'NONE',5,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Bolsa Atleta e valorizar o profissional de educação física.',NULL,'ampliar-o-bolsa-atleta-e-valorizar-o-profissional-de-educacao-fisica',NULL,'NONE',5,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar o Sistema Nacional de Incentivo ao Esporte e ao Lazer.',NULL,'criar-o-sistema-nacional-de-incentivo-ao-esporte-e-ao-lazer',NULL,'NONE',5,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer dos dois eventos um instrumento de inclusão social de crianças e jovens.',NULL,'fazer-dos-dois-eventos-um-instrumento-de-inclusao-social-de-criancas-e-jovens',NULL,'NONE',6,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Qualificar jovens e adultos para atender às demandas criadas pela Copa do Mundo de 2014.',NULL,'qualificar-jovens-e-adultos-para-atender-as-demandas-criadas-pela-copa-do-mundo-de-2014',NULL,'NONE',6,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Vencer o déficit habitacional nesta década.',NULL,'vencer-o-deficit-habitacional-nesta-decada',NULL,'NONE',7,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Contratar a construção de mais dois milhões de moradias no programa Minha Casa, Minha Vida.',NULL,'contratar-a-construcao-de-mais-dois-milhoes-de-moradias-no-programa-minha-casa-minha-vida',NULL,'NONE',7,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incluir eletrodomésticos e móveis na segunda fase do Minha Casa, Minha Vida.',NULL,'incluir-eletrodomesticos-e-moveis-na-segunda-fase-do-minha-casa-minha-vida',NULL,'NONE',7,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar a democratizar o acesso à terra urbana e a regularizar propriedades nos termos da lei.',NULL,'continuar-a-democratizar-o-acesso-a-terra-urbana-e-a-regularizar-propriedades-nos-termos-da-lei',NULL,'NONE',7,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar uma diretoria ou superintendência na Caixa Econômica Federal para investir em habitação rural.',NULL,'criar-uma-diretoria-ou-superintendencia-na-caixa-economica-federal-para-investir-em-habitacao-rural',NULL,'NONE',7,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Investir na prevenção de enchentes no país.',NULL,'investir-na-prevencao-de-enchentes-no-pais',NULL,'NONE',8,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Gastar R$ 11 bilhões em drenagem e proteção de encostas, para combater o problema da ocupação em áreas de risco.',NULL,'gastar-rdollar-11-bilhoes-em-drenagem-e-protecao-de-encostas-para-combater-o-problema-da-ocupacao-em-areas-de-risco',NULL,'NONE',8,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Universalizar o saneamento.',NULL,'universalizar-o-saneamento',NULL,'NONE',8,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Investir R$ 34 bilhões em obras de abastecimento de água e saneamento básico.',NULL,'investir-rdollar-34-bilhoes-em-obras-de-abastecimento-de-agua-e-saneamento-basico',NULL,'NONE',8,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Empenhar-se para promover uma profunda reforma urbana, que beneficie prioritariamente as camadas mais desprotegidas da população.',NULL,'empenhar-se-para-promover-uma-profunda-reforma-urbana-que-beneficie-prioritariamente-as-camadas-mais-desprotegidas-da-populacao',NULL,'NONE',8,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir 2.883 postos de polícia comunitária.',NULL,'construir-2-883-postos-de-policia-comunitaria',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer novo modelo de segurança inspirada nas Unidades de Polícia Pacificadora (UPPs) do Rio.',NULL,'fazer-novo-modelo-de-seguranca-inspirada-nas-unidades-de-policia-pacificadora-(upps)-do-rio',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar e ampliar o Programa Nacional de Segurança Pública (Pronasci), a Bolsa-Formação e o Territórios da Paz.',NULL,'continuar-e-ampliar-o-programa-nacional-de-seguranca-publica-(pronasci)-a-bolsa-formacao-e-o-territorios-da-paz',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Estimular políticas de segurança integradas entre estados, municípios e União.',NULL,'estimular-politicas-de-seguranca-integradas-entre-estados-municipios-e-uniao',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incrementar investimentos em infraestrutura nas áreas com maior índice de violência.',NULL,'incrementar-investimentos-em-infraestrutura-nas-areas-com-maior-indice-de-violencia',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer uma reforma radical no sistema penitenciário e mudar as leis processuais penais.',NULL,'fazer-uma-reforma-radical-no-sistema-penitenciario-e-mudar-as-leis-processuais-penais',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reequipar as Forças Armadas e fortalecer o Ministério da Defesa.',NULL,'reequipar-as-forcas-armadas-e-fortalecer-o-ministerio-da-defesa',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer a Polícia Federal e a Força Nacional de Segurança Pública.',NULL,'fortalecer-a-policia-federal-e-a-forca-nacional-de-seguranca-publica',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar mais capacitação federal às áreas de fronteira e inteligência.',NULL,'dar-mais-capacitacao-federal-as-areas-de-fronteira-e-inteligencia',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o controle das fronteiras para coibir a entrada de armas e de drogas.',NULL,'ampliar-o-controle-das-fronteiras-para-coibir-a-entrada-de-armas-e-de-drogas',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Comprar dez veículos aéreos não tripulados produzidos em Israel.',NULL,'comprar-dez-veiculos-aereos-nao-tripulados-produzidos-em-israel',NULL,'NONE',9,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Lutar contra o crime organizado, especialmente a lavagem de dinheiro, e o roubo de cargas.',NULL,'lutar-contra-o-crime-organizado-especialmente-a-lavagem-de-dinheiro-e-o-roubo-de-cargas',NULL,'NONE',9,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Modernizar o transporte público nas grandes cidades.',NULL,'modernizar-o-transporte-publico-nas-grandes-cidades',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Investir R$ 18 bilhões em obras de transporte público.',NULL,'investir-rdollar-18-bilhoes-em-obras-de-transporte-publico',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Implantar transporte seguro, barato e eficiente.',NULL,'implantar-transporte-seguro-barato-e-eficiente',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o aeroporto Galeão-Tom Jobim, com a conclusão do terminal 2 e melhorias no terminal 1.',NULL,'ampliar-o-aeroporto-galeao-tom-jobim-com-a-conclusao-do-terminal-2-e-melhorias-no-terminal-1',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer novos aeroportos em Goiânia, Cuiabá e Porto Seguro (BA).',NULL,'fazer-novos-aeroportos-em-goiania-cuiaba-e-porto-seguro-(ba)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar os aeroportos Afonso Pena (Curitiba) e Guarulhos.',NULL,'ampliar-os-aeroportos-afonso-pena-(curitiba)-e-guarulhos',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer nova pista no aeroporto de Confins (Belo Horizonte).',NULL,'fazer-nova-pista-no-aeroporto-de-confins-(belo-horizonte)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir o aeroporto de São Gonçalo do Amarante (RN).',NULL,'construir-o-aeroporto-de-sao-goncalo-do-amarante-(rn)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer o trem de alta velocidade entre Rio e São Paulo.',NULL,'fazer-o-trem-de-alta-velocidade-entre-rio-e-sao-paulo',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir e construir metrôs nas principais aglomerações urbanas.',NULL,'expandir-e-construir-metros-nas-principais-aglomeracoes-urbanas',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o Trensurb, em Porto Alegre.',NULL,'ampliar-o-trensurb-em-porto-alegre',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Duplicar as rodovias BR-116 e BR-386, no Rio Grande do Sul.',NULL,'duplicar-as-rodovias-br-116-e-br-386-no-rio-grande-do-sul',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Estender a rodovia BR-110 (RN).',NULL,'estender-a-rodovia-br-110-(rn)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Duplicar e melhorar as estradas Manaus-Porto Velho, Cuiabá-Santarém, BR-060 (em Goiás), BR-470 (em Santa Catarina), BR-381 (de Belo Horizonte a Governador Valadares, em Minas) e BR-040 (de Belo Horizonte ao Rio).',NULL,'duplicar-e-melhorar-as-estradas-manaus-porto-velho-cuiaba-santarem-br-060-(em-goias)-br-470-(em-santa-catarina)-br-381-(de-belo-horizonte-a-governador-valadares-em-minas)-e-br-040-(de-belo-horizonte-ao-rio)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Concluir a Via Expressa em Salvador.',NULL,'concluir-a-via-expressa-em-salvador',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar e modernizar os portos de Salvador, Vitória, Itaqui (MA), Suape (PE) e Cabedelo (PB).',NULL,'ampliar-e-modernizar-os-portos-de-salvador-vitoria-itaqui-(ma)-suape-(pe)-e-cabedelo-(pb)',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer 51 grandes obras viárias, como novos corredores de transporte, mais metrô e veículos leve sobre trilhos.',NULL,'fazer-51-grandes-obras-viarias-como-novos-corredores-de-transporte-mais-metro-e-veiculos-leve-sobre-trilhos',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Eliminar os gargalos que limitam o crescimento econômico, especialmente em transportes e condições de armazenagem.',NULL,'eliminar-os-gargalos-que-limitam-o-crescimento-economico-especialmente-em-transportes-e-condicoes-de-armazenagem',NULL,'NONE',10,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Investir em transporte de carga.',NULL,'investir-em-transporte-de-carga',NULL,'NONE',10,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar reajustando o salário-mínimo acima da inflação.',NULL,'continuar-reajustando-o-salario-minimo-acima-da-inflacao',NULL,'NONE',11,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar as condições para repetir a criação de 14 milhões a 15 milhões de empregos com carteira assinada.',NULL,'criar-as-condicoes-para-repetir-a-criacao-de-14-milhoes-a-15-milhoes-de-empregos-com-carteira-assinada',NULL,'NONE',11,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer do Brasil um país de pleno emprego.',NULL,'fazer-do-brasil-um-pais-de-pleno-emprego',NULL,'NONE',11,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter diálogo com os sindicatos para definir as grandes linhas das políticas trabalhistas.',NULL,'manter-dialogo-com-os-sindicatos-para-definir-as-grandes-linhas-das-politicas-trabalhistas',NULL,'NONE',11,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Combater o trabalho infantil e degradante, especialmente as manifestações residuais de trabalho escravo.',NULL,'combater-o-trabalho-infantil-e-degradante-especialmente-as-manifestacoes-residuais-de-trabalho-escravo',NULL,'NONE',11,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar atenção especial ao acesso de jovens e pessoas de segmentos mais discriminados ao mercado formal de trabalho.',NULL,'dar-atencao-especial-ao-acesso-de-jovens-e-pessoas-de-segmentos-mais-discriminados-ao-mercado-formal-de-trabalho',NULL,'NONE',11,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir a zero os tributos sobre investimentos para aumentar a taxa de crescimento do país.',NULL,'reduzir-a-zero-os-tributos-sobre-investimentos-para-aumentar-a-taxa-de-crescimento-do-pais',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir os impostos cobrados de empresas de ônibus, com obrigação de repasse do benefício para o preço das passagens.',NULL,'reduzir-os-impostos-cobrados-de-empresas-de-onibus-com-obrigacao-de-repasse-do-beneficio-para-o-preco-das-passagens',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir os impostos sobre empresas de saneamento para impulsionar mais obras de água e esgoto.',NULL,'reduzir-os-impostos-sobre-empresas-de-saneamento-para-impulsionar-mais-obras-de-agua-e-esgoto',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir os tributos sobre energia elétrica.',NULL,'reduzir-os-tributos-sobre-energia-eletrica',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir os impostos sobre a folha de pagamento das empresas para estimular a geração de mais empregos.',NULL,'reduzir-os-impostos-sobre-a-folha-de-pagamento-das-empresas-para-estimular-a-geracao-de-mais-empregos',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Possibilitar a devolução imediata do crédito de ICMS às empresas exportadoras.',NULL,'possibilitar-a-devolucao-imediata-do-credito-de-icms-as-empresas-exportadoras',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incentivar uma reforma para simplificar os tributos, mesmo que seja de forma fatiada.',NULL,'incentivar-uma-reforma-para-simplificar-os-tributos-mesmo-que-seja-de-forma-fatiada',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Trabalhar para acabar com a guerra fiscal entre os estados.',NULL,'trabalhar-para-acabar-com-a-guerra-fiscal-entre-os-estados',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Defender a desoneração da folha de salários. Para não prejudicar o financiamento à Previdência, o Tesouro faria a compensação.',NULL,'defender-a-desoneracao-da-folha-de-salarios-para-nao-prejudicar-o-financiamento-a-previdencia-o-tesouro-faria-a-compensacao',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Trabalhar para garantir a devolução automática de todos os créditos a que as empresas têm direito. Possibilitar a devolução imediata do crédito de ICMS às empresas exportadoras.',NULL,'trabalhar-para-garantir-a-devolucao-automatica-de-todos-os-creditos-a-que-as-empresas-tem-direito-possibilitar-a-devolucao-imediata-do-credito-de-icms-as-empresas-exportadoras',NULL,'NONE',12,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Informatizar o sistema de tributos para alargar a base da arrecadação e diminuir as alíquotas.',NULL,'informatizar-o-sistema-de-tributos-para-alargar-a-base-da-arrecadacao-e-diminuir-as-aliquotas',NULL,'NONE',12,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Combater a corrupção.',NULL,'combater-a-corrupcao',NULL,'NONE',13,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ter critérios tanto políticos quanto técnicos para preencher cargos públicos.',NULL,'ter-criterios-tanto-politicos-quanto-tecnicos-para-preencher-cargos-publicos',NULL,'NONE',13,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Concretizar, com o Congresso, as reformas institucionais, como a política e a tributária.',NULL,'concretizar-com-o-congresso-as-reformas-institucionais-como-a-politica-e-a-tributaria',NULL,'NONE',13,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não promover a reforma da Previdência, mas pode ser feito um \"ajuste marginal\".',NULL,'nao-promover-a-reforma-da-previdencia-mas-pode-ser-feito-um-\"ajuste-marginal\"',NULL,'NONE',13,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer o PAC 2, com mais força nas áreas de habitação, saúde, educação e segurança.',NULL,'fazer-o-pac-2-com-mais-forca-nas-areas-de-habitacao-saude-educacao-e-seguranca',NULL,'NONE',13,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Estimular a parceria entre os setores público e privado.',NULL,'estimular-a-parceria-entre-os-setores-publico-e-privado',NULL,'NONE',13,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não fazer ajuste fiscal (o clássico, com corte indiscriminado de gastos), mas não abandonar a estabilidade ou o controle de despesas.',NULL,'nao-fazer-ajuste-fiscal-(o-classico-com-corte-indiscriminado-de-gastos)-mas-nao-abandonar-a-estabilidade-ou-o-controle-de-despesas',NULL,'NONE',14,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer uma reforma do Estado para dar mais transparência ao governo e eficácia no combate à corrupção.',NULL,'fazer-uma-reforma-do-estado-para-dar-mais-transparencia-ao-governo-e-eficacia-no-combate-a-corrupcao',NULL,'NONE',14,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Elevar a poupança e o investimento público, estimulando também o investimento privado.',NULL,'elevar-a-poupanca-e-o-investimento-publico-estimulando-tambem-o-investimento-privado',NULL,'NONE',14,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter o controle da inflação. ',NULL,'manter-o-controle-da-inflacao',NULL,'NONE',15,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter o câmbio flutuante.',NULL,'manter-o-cambio-flutuante',NULL,'NONE',15,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Trabalhar para reduzir fortemente os juros. Para isso, reduzir a dívida líquida em relação ao PIB para cerca de 30% em 2014.',NULL,'trabalhar-para-reduzir-fortemente-os-juros-para-isso-reduzir-a-divida-liquida-em-relacao-ao-pib-para-cerca-de-30-em-2014',NULL,'NONE',15,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Agregar valor às riquezas do país e produzir tudo o que for possível no Brasil.',NULL,'agregar-valor-as-riquezas-do-pais-e-produzir-tudo-o-que-for-possivel-no-brasil',NULL,'NONE',16,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir a indústria naval.',NULL,'expandir-a-industria-naval',NULL,'NONE',16,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir cinco refinarias, uma delas a Abreu e Lima (PE), com tecnologia de ponta.',NULL,'construir-cinco-refinarias-uma-delas-a-abreu-e-lima-(pe)-com-tecnologia-de-ponta',NULL,'NONE',16,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Defender a abertura de capital da Infraero, mantendo controle estatal.',NULL,'defender-a-abertura-de-capital-da-infraero-mantendo-controle-estatal',NULL,'NONE',16,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Rever o marco regulatório da mineração, para aumentar a arrecadação de royalties.',NULL,'rever-o-marco-regulatorio-da-mineracao-para-aumentar-a-arrecadacao-de-royalties',NULL,'NONE',16,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Criar um ministério para pequenas e médias empresas.',NULL,'criar-um-ministerio-para-pequenas-e-medias-empresas',NULL,'NONE',17,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer a política de microcrédito.',NULL,'fortalecer-a-politica-de-microcredito',NULL,'NONE',17,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o limite de enquadramento no Super Simples e no Microempreendedor individual.',NULL,'ampliar-o-limite-de-enquadramento-no-super-simples-e-no-microempreendedor-individual',NULL,'NONE',17,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Estimular e favorecer o empreendedorismo, com políticas tributárias, de crédito, ambientais, de suporte tecnológico, de qualificação profissional e de ampliação de mercados.',NULL,'estimular-e-favorecer-o-empreendedorismo-com-politicas-tributarias-de-credito-ambientais-de-suporte-tecnologico-de-qualificacao-profissional-e-de-ampliacao-de-mercados',NULL,'NONE',17,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Defender tratamento diferenciado aos estados produtores na distribuição de royalties do petróleo.',NULL,'defender-tratamento-diferenciado-aos-estados-produtores-na-distribuicao-de-royalties-do-petroleo',NULL,'NONE',18,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Usar os recursos do pré-sal em educação, saúde, cultura, combate à pobreza, meio ambiente, ciência e tecnologia.',NULL,'usar-os-recursos-do-pre-sal-em-educacao-saude-cultura-combate-a-pobreza-meio-ambiente-ciencia-e-tecnologia',NULL,'NONE',18,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Com os recursos do pré-sal, tornar o Brasil a quinta maior economia do mundo.',NULL,'com-os-recursos-do-pre-sal-tornar-o-brasil-a-quinta-maior-economia-do-mundo',NULL,'NONE',18,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não privatizar a Petrobras e o pré-sal.',NULL,'nao-privatizar-a-petrobras-e-o-pre-sal',NULL,'NONE',18,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer uma política com ênfase na produção de energia renovável e na pesquisa de novas fontes limpas. Construir parques eólicos.',NULL,'fazer-uma-politica-com-enfase-na-producao-de-energia-renovavel-e-na-pesquisa-de-novas-fontes-limpas-construir-parques-eolicos',NULL,'NONE',19,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Desenvolver o potencial hidrelétrico do país.',NULL,'desenvolver-o-potencial-hidreletrico-do-pais',NULL,'NONE',19,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar a liderança mundial do Brasil na produção de energia limpa.',NULL,'ampliar-a-lideranca-mundial-do-brasil-na-producao-de-energia-limpa',NULL,'NONE',19,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir o etanol na matriz energética brasileira e ampliar a participação do combustível na matriz mundial.',NULL,'expandir-o-etanol-na-matriz-energetica-brasileira-e-ampliar-a-participacao-do-combustivel-na-matriz-mundial',NULL,'NONE',19,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incentivar a produção de biocombustíveis.',NULL,'incentivar-a-producao-de-biocombustiveis',NULL,'NONE',19,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir em 80% o desmatamento na Amazônia.',NULL,'reduzir-em-80-o-desmatamento-na-amazonia',NULL,'NONE',20,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ter tolerância zero com desmatamento em qualquer bioma.',NULL,'ter-tolerancia-zero-com-desmatamento-em-qualquer-bioma',NULL,'NONE',20,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incentivar o reflorestamento em áreas degradadas.',NULL,'incentivar-o-reflorestamento-em-areas-degradadas',NULL,'NONE',20,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Antecipar o cumprimento da meta de reduzir as emissões de gases do efeito estufa em 36% a 39% até 2020.',NULL,'antecipar-o-cumprimento-da-meta-de-reduzir-as-emissoes-de-gases-do-efeito-estufa-em-36-a-39-ate-2020',NULL,'NONE',20,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar prioridade à economia de baixo carbono, consolidando o modelo de energia renovável.',NULL,'dar-prioridade-a-economia-de-baixo-carbono-consolidando-o-modelo-de-energia-renovavel',NULL,'NONE',20,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Considerar critérios ambientais nas políticas industrial, fiscal e de crédito.',NULL,'considerar-criterios-ambientais-nas-politicas-industrial-fiscal-e-de-credito',NULL,'NONE',20,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Reduzir as invasões no campo.',NULL,'reduzir-as-invasoes-no-campo',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não compactuar com invasões de prédios públicos e propriedades, mas não reprimir manifestações de sem-terra quando forem simples reivindicações.',NULL,'nao-compactuar-com-invasoes-de-predios-publicos-e-propriedades-mas-nao-reprimir-manifestacoes-de-sem-terra-quando-forem-simples-reivindicacoes',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Intensificar e aprimorar a reforma agrária para dar centralidade à estratégia de desenvolvimento sustentável, com a garantia do cumprimento integral da função social da propriedade.',NULL,'intensificar-e-aprimorar-a-reforma-agraria-para-dar-centralidade-a-estrategia-de-desenvolvimento-sustentavel-com-a-garantia-do-cumprimento-integral-da-funcao-social-da-propriedade',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o financiamento para o agronegócio e a agricultura familiar.',NULL,'ampliar-o-financiamento-para-o-agronegocio-e-a-agricultura-familiar',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Assegurar crédito, assistência técnica e mercado aos pequenos produtores. Ampliar o programa de compra direta de alimentos do agricultor familiar, passando de 700 mil para 1,2 milhão de contemplados. Ao mesmo tempo, apoiar os grandes produtores, que contr',NULL,'assegurar-credito-assistencia-tecnica-e-mercado-aos-pequenos-produtores-ampliar-o-programa-de-compra-direta-de-alimentos-do-agricultor-familiar-passando-de-700-mil-para-12-milhao-de-contemplados-ao-mesmo-tempo-apoiar-os-grandes-produtores-que-contr',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Incluir dois milhões de famílias de pequenos agricultores e assentados no Programa Nacional de Fortalecimento da Agricultura Familiar (Pronaf).',NULL,'incluir-dois-milhoes-de-familias-de-pequenos-agricultores-e-assentados-no-programa-nacional-de-fortalecimento-da-agricultura-familiar-(pronaf)',NULL,'NONE',21,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar mais apoio científico e tecnológico a organismos como a Embrapa.',NULL,'dar-mais-apoio-cientifico-e-tecnologico-a-organismos-como-a-embrapa',NULL,'NONE',21,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer 54 obras para melhorar os indicadores de saúde das comunidades ribeirinhas da Região Norte.',NULL,'fazer-54-obras-para-melhorar-os-indicadores-de-saude-das-comunidades-ribeirinhas-da-regiao-norte',NULL,'NONE',22,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Construir sistemas de irrigação no Sul, no Sudeste e no Centro-Oeste.',NULL,'construir-sistemas-de-irrigacao-no-sul-no-sudeste-e-no-centro-oeste',NULL,'NONE',22,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar a transposição das águas do Rio São Francisco.',NULL,'continuar-a-transposicao-das-aguas-do-rio-sao-francisco',NULL,'NONE',22,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não mandar ao Congresso ou sancionar qualquer legislação que impacte a religião, como legalização do aborto e casamento homossexual. ',NULL,'nao-mandar-ao-congresso-ou-sancionar-qualquer-legislacao-que-impacte-a-religiao-como-legalizacao-do-aborto-e-casamento-homossexual',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Tratar o aborto como questão de saúde pública, atendendo às mulheres que tenham abortado e enfrentem risco de morrer.',NULL,'tratar-o-aborto-como-questao-de-saude-publica-atendendo-as-mulheres-que-tenham-abortado-e-enfrentem-risco-de-morrer',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Sancionar o projeto de lei complementar 122 (que criminaliza a homofobia) apenas nos artigos que não violem a liberdade de crença, de culto e de expressão e as demais garantias constitucionais individuais.',NULL,'sancionar-o-projeto-de-lei-complementar-122-(que-criminaliza-a-homofobia)-apenas-nos-artigos-que-nao-violem-a-liberdade-de-crenca-de-culto-e-de-expressao-e-as-demais-garantias-constitucionais-individuais',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer da família o foco principal de seu governo.',NULL,'fazer-da-familia-o-foco-principal-de-seu-governo',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não promover iniciativas que afrontem a família.',NULL,'nao-promover-iniciativas-que-afrontem-a-familia',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fazer leis e programas que tenham a família como foco.',NULL,'fazer-leis-e-programas-que-tenham-a-familia-como-foco',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Defender a convivência entre as diferentes religiões.',NULL,'defender-a-convivencia-entre-as-diferentes-religioes',NULL,'NONE',23,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter diálogo com as igrejas.',NULL,'manter-dialogo-com-as-igrejas',NULL,'NONE',23,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer o Sistema Nacional de Cultura.',NULL,'fortalecer-o-sistema-nacional-de-cultura',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar a produção e o consumo de bens culturais com base na diversidade brasileira.',NULL,'ampliar-a-producao-e-o-consumo-de-bens-culturais-com-base-na-diversidade-brasileira',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar meios e oportunidades à criatividade popular.',NULL,'dar-meios-e-oportunidades-a-criatividade-popular',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar os pontos de cultura e outros equipamentos.',NULL,'ampliar-os-pontos-de-cultura-e-outros-equipamentos',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Implantar o Vale Cultura.',NULL,'implantar-o-vale-cultura',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer a indústria do audiovisual nacional e regional em articulação com outros países, sobretudo do Sul.',NULL,'fortalecer-a-industria-do-audiovisual-nacional-e-regional-em-articulacao-com-outros-paises-sobretudo-do-sul',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Aperfeiçoar os mecanismos de financiamento da cultura.',NULL,'aperfeicoar-os-mecanismos-de-financiamento-da-cultura',NULL,'NONE',24,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer a presença cultural do Brasil no mundo e promover o diálogo com outras culturas.',NULL,'fortalecer-a-presenca-cultural-do-brasil-no-mundo-e-promover-o-dialogo-com-outras-culturas',NULL,'NONE',24,1,1);

insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Não censurar conteúdo e rejeitar qualquer tentativa de controlar a mídia.',NULL,'nao-censurar-conteudo-e-rejeitar-qualquer-tentativa-de-controlar-a-midia',NULL,'NONE',25,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Dar garantia irrestrita da liberdade de imprensa, de expressão e de religião.',NULL,'dar-garantia-irrestrita-da-liberdade-de-imprensa-de-expressao-e-de-religiao',NULL,'NONE',25,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Expandir e fortalecer a democracia política, econômica e social.',NULL,'expandir-e-fortalecer-a-democracia-politica-economica-e-social',NULL,'NONE',25,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Fortalecer as redes públicas de comunicação e estimular o uso intensivo da blogosfera.',NULL,'fortalecer-as-redes-publicas-de-comunicacao-e-estimular-o-uso-intensivo-da-blogosfera',NULL,'NONE',25,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar o acesso aos meios de informação e comunicação por meio de internet, TV aberta e novas tecnologias.',NULL,'ampliar-o-acesso-aos-meios-de-informacao-e-comunicacao-por-meio-de-internet-tv-aberta-e-novas-tecnologias',NULL,'NONE',25,1,1);
  
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Ampliar a presença internacional do Brasil, defendendo a paz, a redução de armamentos e uma ordem econômica e política mais justa.',NULL,'ampliar-a-presenca-internacional-do-brasil-defendendo-a-paz-a-reducao-de-armamentos-e-uma-ordem-economica-e-politica-mais-justa',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Permanecer fiel aos princípios de não intervenção e direitos humanos.',NULL,'permanecer-fiel-aos-principios-de-nao-intervencao-e-direitos-humanos',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Defender a democratização de organismos multilaterais como a ONU, o FMI e o Banco Mundial.',NULL,'defender-a-democratizacao-de-organismos-multilaterais-como-a-onu-o-fmi-e-o-banco-mundial',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter a política de Lula, com diversificação de parceiros comerciais.',NULL,'manter-a-politica-de-lula-com-diversificacao-de-parceiros-comerciais',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Manter olhar especial para a África.',NULL,'manter-olhar-especial-para-a-africa',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Continuar a integração sul-americana e latino-americana e a cooperação Sul-Sul.',NULL,'continuar-a-integracao-sul-americana-e-latino-americana-e-a-cooperacao-sul-sul',NULL,'NONE',26,1,1);
insert into promise (title, description, slug, evidence_date, state, category_id, politician_id, registered_by_user_id) values ('Prestar solidariedade aos países pobres e em desenvolvimento.',NULL,'prestar-solidariedade-aos-paises-pobres-e-em-desenvolvimento',NULL,'NONE',26,1,1);