insert into state (id, uf, name, preposition) values (12, 'AC', 'Acre', 'no');
insert into state (id, uf, name, preposition) values (27, 'AL', 'Alagoas', 'em');
insert into state (id, uf, name, preposition) values (13, 'AM', 'Amazonas', 'no');
insert into state (id, uf, name, preposition) values (16, 'AP', 'Amapá', 'no');
insert into state (id, uf, name, preposition) values (29, 'BA', 'Bahia', 'na');
insert into state (id, uf, name, preposition) values (23, 'CE', 'Ceará', 'no');
insert into state (id, uf, name, preposition) values (53, 'DF', 'Distrito Federal', 'no');
insert into state (id, uf, name, preposition) values (32, 'ES', 'Espírito Santo', 'no');
insert into state (id, uf, name, preposition) values (52, 'GO', 'Goiás', 'em');
insert into state (id, uf, name, preposition) values (21, 'MA', 'Maranhão', 'no');
insert into state (id, uf, name, preposition) values (31, 'MG', 'Minas Gerais', 'em');
insert into state (id, uf, name, preposition) values (50, 'MS', 'Mato Grosso do Sul', 'em');
insert into state (id, uf, name, preposition) values (51, 'MT', 'Mato Grosso', 'em');
insert into state (id, uf, name, preposition) values (15, 'PA', 'Pará', 'no');
insert into state (id, uf, name, preposition) values (25, 'PB', 'Paraíba', 'na');
insert into state (id, uf, name, preposition) values (26, 'PE', 'Pernambuco', 'em');
insert into state (id, uf, name, preposition) values (22, 'PI', 'Piauí', 'no');
insert into state (id, uf, name, preposition) values (41, 'PR', 'Paraná', 'no');
insert into state (id, uf, name, preposition) values (33, 'RJ', 'Rio de Janeiro', 'no');
insert into state (id, uf, name, preposition) values (24, 'RN', 'Rio Grande do Norte', 'no');
insert into state (id, uf, name, preposition) values (11, 'RO', 'Rondônia', 'em');
insert into state (id, uf, name, preposition) values (14, 'RR', 'Roraima', 'em');
insert into state (id, uf, name, preposition) values (43, 'RS', 'Rio Grande do Sul', 'no');
insert into state (id, uf, name, preposition) values (42, 'SC', 'Santa Catarina', 'em');
insert into state (id, uf, name, preposition) values (28, 'SE', 'Sergipe', 'em');
insert into state (id, uf, name, preposition) values (35, 'SP', 'São Paulo', 'em');
insert into state (id, uf, name, preposition) values (17, 'TO', 'Tocantins', 'em');

insert into user (id, name, gender, permission, username, email, facebook_account, twitter_account, google_account, registration_date) values (1, 'Sandro Simas', 'MALE', 'ADMIN', 'sandro.csimas', 'sandro.csimas@gmail.com', '654264634643651', null, null, '2014-04-27 11:19:10');

insert into political_party (id, acronym, name) values (1, 'PMDB', 'Partido do Movimento Democrático Brasileiro');
insert into political_party (id, acronym, name) values (2, 'PTB', 'Partido Trabalhista');
insert into political_party (id, acronym, name) values (3, 'PDT', 'Partido Democrático Trabalhista');
insert into political_party (id, acronym, name) values (4, 'PT', 'Partido dos Trabalhadores');
insert into political_party (id, acronym, name) values (5, 'DEM', 'Democratas');
insert into political_party (id, acronym, name) values (6, 'PCdoB', 'Partido Comunista do Brasil');
insert into political_party (id, acronym, name) values (7, 'PSB', 'Partido Socialista Brasileiro');
insert into political_party (id, acronym, name) values (8, 'PSDB', 'Partido da Social Democracia Brasileira');
insert into political_party (id, acronym, name) values (9, 'PTC', 'Partido Trabalhista Cristão');
insert into political_party (id, acronym, name) values (10, 'PSC', 'Partido Social Cristão');
insert into political_party (id, acronym, name) values (11, 'PMN', 'Partido da Mobilização Nacional');
insert into political_party (id, acronym, name) values (12, 'PRP', 'Partido Republicano Progressista');
insert into political_party (id, acronym, name) values (13, 'PPS', 'Partido Popular Socialista');
insert into political_party (id, acronym, name) values (14, 'PV', 'Partido Verde');
insert into political_party (id, acronym, name) values (15, 'PTdoB', 'Partido Trabalhista do Brasil');
insert into political_party (id, acronym, name) values (16, 'PP', 'Partido Progressista');
insert into political_party (id, acronym, name) values (17, 'PSTU', 'Partido Socialista dos Trabalhadores Unificado');
insert into political_party (id, acronym, name) values (18, 'PCB', 'Partido Comunista Brasileiro');
insert into political_party (id, acronym, name) values (19, 'PRTB', 'Partido Renovador Trabalhista Brasileiro');
insert into political_party (id, acronym, name) values (20, 'PHS', 'Partido Humanista da Solidariedade');
insert into political_party (id, acronym, name) values (21, 'PSDC', 'Partido Social Democrata Cristão');
insert into political_party (id, acronym, name) values (22, 'PCO', 'Partido da Causa Operária');
insert into political_party (id, acronym, name) values (23, 'PTN', 'Partido Trabalhista Nacional');
insert into political_party (id, acronym, name) values (24, 'PSL', 'Partido Social Liberal');
insert into political_party (id, acronym, name) values (25, 'PRB', 'Partido Republicano Brasileiro');
insert into political_party (id, acronym, name) values (26, 'PSOL', 'Partido Socialismo e Liberdade');
insert into political_party (id, acronym, name) values (27, 'PR', 'Partido da República');
insert into political_party (id, acronym, name) values (28, 'PSD', 'Partido Social Democrático');
insert into political_party (id, acronym, name) values (29, 'PPL', 'Partido Pátria Livre');
insert into political_party (id, acronym, name) values (30, 'PEN', 'Partido Ecológico Nacional');
insert into political_party (id, acronym, name) values (31, 'PROS', 'Partido Republicano da Ordem Social');
insert into political_party (id, acronym, name) values (32, 'SD', 'Solidariedade');

insert into political_office (id, title) values (1, 'Presidente');
insert into political_office (id, title) values (2, 'Senador');
insert into political_office (id, title) values (3, 'Deputado');
insert into political_office (id, title) values (4, 'Governador');
insert into political_office (id, title) values (5, 'Prefeito');
insert into political_office (id, title) values (6, 'Vereador');

insert into promise_category (id, name, slug) values (1, 'Saúde', 'saude');
insert into promise_category (id, name, slug) values (2, 'Programas Sociais e de Inclusão', 'programas-sociais-e-inclusao');
insert into promise_category (id, name, slug) values (3, 'Educação e Qualificação', 'educacao-e-qualificacao');
insert into promise_category (id, name, slug) values (4, 'Ciência e Tecnologia', 'ciencia-e-tecnologia');
insert into promise_category (id, name, slug) values (5, 'Esporte e Lazer', 'esporte-e-lazer');
insert into promise_category (id, name, slug) values (6, 'Copa e Olimpíadas', 'copa-e-olimpiadas');
insert into promise_category (id, name, slug) values (7, 'Habitação', 'habitacao');
insert into promise_category (id, name, slug) values (8, 'Urbanização', 'urbanizacao');
insert into promise_category (id, name, slug) values (9, 'Segurança e Defesa', 'seguranca-e-defesa');
insert into promise_category (id, name, slug) values (10, 'Mobilidade Urbana, Transporte e Infraestrutura', 'mobilidade-urbana-transporte-e-infraestrutura');
insert into promise_category (id, name, slug) values (11, 'Emprego e Renda', 'emprego-e-renda');
insert into promise_category (id, name, slug) values (12, 'Impostos', 'impostos');
insert into promise_category (id, name, slug) values (13, 'Administração', 'administracao');
insert into promise_category (id, name, slug) values (14, 'Contas Públicas', 'contas-publicas');
insert into promise_category (id, name, slug) values (15, 'Macroeconomia e Finanças', 'macroeconomia-e-financas');
insert into promise_category (id, name, slug) values (16, 'Indústria', 'industria');
insert into promise_category (id, name, slug) values (17, 'Pequenas Empresas', 'pequenas-empresas');
insert into promise_category (id, name, slug) values (18, 'Petróleo', 'petroleo');
insert into promise_category (id, name, slug) values (19, 'Outras Fontes de Energia', 'outras-fontes-de-energia');
insert into promise_category (id, name, slug) values (20, 'Meio Ambiente e Sustentabilidade', 'meio-ambiente-e-sustentabilidade');
insert into promise_category (id, name, slug) values (21, 'Reforma Agrária e Agricultura', 'reforma-agraria-e-agricultura');
insert into promise_category (id, name, slug) values (22, 'Irrigação', 'irrigacao');
insert into promise_category (id, name, slug) values (23, 'Família e Religião', 'familia-e-religiao');
insert into promise_category (id, name, slug) values (24, 'Cultura', 'cultura');
insert into promise_category (id, name, slug) values (25, 'Mídia e Livre Expressão', 'midia-e-livre-expressao');
insert into promise_category (id, name, slug) values (26, 'Política Externa', 'politica-externa');
insert into promise_category (id, name, slug) values (27, 'Servidor Público', 'servidor-publico');